//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSport.WinUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eSport.WinUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj telefona mora biti u formatu 000-000-000 ili 000-000-0000.
        /// </summary>
        internal static string BrojTelefonaValidacija {
            get {
                return ResourceManager.GetString("BrojTelefonaValidacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj timova mora biti minimalno 3..
        /// </summary>
        internal static string BrojTimova {
            get {
                return ResourceManager.GetString("BrojTimova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potreban je email format. (naziv@emailadresa.domena).
        /// </summary>
        internal static string EmailValidacija {
            get {
                return ResourceManager.GetString("EmailValidacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Došlo je do greške..
        /// </summary>
        internal static string Greška {
            get {
                return ResourceManager.GetString("Greška", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrani teren ne možete obrisati. Potrebno je da prvo aktivne termine i turnire koji se održavaju na ovom terenu zamijenite drugim..
        /// </summary>
        internal static string GreškaUBrisanjuTerena {
            get {
                return ResourceManager.GetString("GreškaUBrisanjuTerena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešni kredencijali..
        /// </summary>
        internal static string GreškaUPrijavi {
            get {
                return ResourceManager.GetString("GreškaUPrijavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik sa istim korisničkim imenom već postoji, molimo stavite drugo..
        /// </summary>
        internal static string KorisnickoImeVecPostoji {
            get {
                return ResourceManager.GetString("KorisnickoImeVecPostoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemate permisije za ovu operaciju..
        /// </summary>
        internal static string NemaPermisija {
            get {
                return ResourceManager.GetString("NemaPermisija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nema podataka..
        /// </summary>
        internal static string NemaPodataka {
            get {
                return ResourceManager.GetString("NemaPodataka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno polje..
        /// </summary>
        internal static string ObavezanUnosPolja {
            get {
                return ResourceManager.GetString("ObavezanUnosPolja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno..
        /// </summary>
        internal static string UspješnaOperacija {
            get {
                return ResourceManager.GetString("UspješnaOperacija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabrani termin vec je zauzet, probajte drugi datum ili drugo vrijeme..
        /// </summary>
        internal static string Zauzeto {
            get {
                return ResourceManager.GetString("Zauzeto", resourceCulture);
            }
        }
    }
}
